### ISSUE TITLE
Flight End UI

### ISSUE THREAD

**Issue by SMaleck** [SMaleck/kick-the-jester#27]
Flight End UI is a enclosed component, which shows up when the round ends.

It offers
- a way to start a new round
- a way to get to the shop

It shows
- the distance achieved
- the best distance achived
- the money collected
- the money earned for the distance
- the total amount of money made

The user cannot press the pause button while in this UI (protip: easily achievable by putting a fullscreen invisible panel above all else :D )

**Comment by jonashartmann** [comment]
> protip: easily achievable by putting a fullscreen invisible panel above all else :D
Or simply making the whole back panel fullscreen already :)

**Comment by jonashartmann** [comment]
Points left to be done:

- the money collected
- the money earned for the distance
- the total amount of money made
