### ISSUE TITLE
Convert PlayerProfile Properties to UniRx

### ISSUE THREAD

**Issue by SMaleck** [SMaleck/kick-the-jester#33]
PlayerProfile is still using regular EventHandlers.

* Move PlayerProfile to Repositories NameSpace
* Refactor all reactive properties to use UniRx
* Refactor all dependent classes to use the UniRx style

**Comment by jonashartmann** [comment]
- [x] Move PlayerProfile to Repositories NameSpace
- [x] Refactor all reactive properties to use UniRx
- [x] Refactor all dependent classes to use the UniRx style
